# https://taskfile.dev

## Build Management only for go

version: '2'

env:
  AWS_DEFAULT_REGION: eu-central-1

tasks:

  deploy:
    desc: Deploy only lambda
    cmds:
      - mkdir -p dist
      - zip -r dist/index.zip index.js
      - aws lambda update-function-code --function-name  challenge-policy --zip-file fileb://dist/index.zip